# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-12.16
packages:
- .
extra-deps:
- ../fei-nn
- ../fei-base
- ../tuple-ops
- git: https://github.com/kylcarte/type-combinators.git
  commit: 071942730b6bb34990d37e1a25236382cf0dcbc6
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- hlint-2.1.17
- unordered-containers-0.2.10.0
- hip-1.5.4.0
- c2hs-extra-0.1.0.1
extra-include-dirs:
- /home/jiasen/hdd/dschungel/incubator-mxnet-1.5/include
extra-lib-dirs:
- /home/jiasen/hdd/dschungel/incubator-mxnet-1.5/lib
flags:
  fei-base:
    MXNet_1_5: true
